### ISSUE TITLE
needlessly depends on oxigraph

### ISSUE THREAD

**Issue by jonassmedegaard** [weso/shapes-rs#103]
This project declares a dependency on oxigraph, but that crate is not used anywhere in the code.

Please consider adopting [this patch](https://salsa.debian.org/debian/rdfsx/-/blob/debian/latest/debian/patches/1002_oxigraph.patch) to reduce compile time by 15-20 percent seemingly with no ill effects.

**Comment by labra** [comment]
Thanks for the patch...applied it and seems to work!
