### ISSUE TITLE
root crate needlessly duplicates crate rdfsx_cli

### ISSUE THREAD

**Issue by jonassmedegaard** [weso/shapes-rs#104]
There is effort to setup the root crate as a virtual workspace, but that seems little used, and instead it is used for building the executable binary for crate rdfsx_cli, simply renamed.

Please consider adopting [this patch](https://salsa.debian.org/debian/rdfsx/-/blob/debian/latest/debian/patches/1003_workspace.patch) (on top of #103) to convert the root crate to a virtual workspace, and have rdfsx_cli itself build its executable under the custom name.

**Comment by labra** [comment]
Thanks for the patch...applied it and it seems to work...next step now, to rename rdfsx to rudof
