### ISSUE TITLE
SHACL validation

### ISSUE THREAD

**Issue by labra** [weso/shapes-rs#22]
Add SHACL validation

**Comment by MarcAntoine-Arnaud** [comment]
Does the SHex validator may be relevant to used for it ?
My question behind is, can we create a crate `shape_validation` and `shacl_validation` & `shex_validation` may just use the same validator ?

**Comment by labra** [comment]
In principle, it would make sense. 

In [SHaclEX](https://github.com/weso/shaclex), I tried to do that, but I was not very successful because the shaclex module depended on [shex-s](https://github.com/weso/shex-s) and [shacl-s](https://github.com/weso/shacl-s), and I think your proposal would be to have shex_validator and `shacl_validation` depend on a common module called `shape_validation`, which could make sense.

My plan was to start a crate called `shacl_validation` soon (mybe in two-three weeks), but if you want to start it, that would be fine.  

@angelip2303 was also planning to work on it, so you could collaborate.

**Comment by angelip2303** [comment]
Yeah, would be nice to have a common module for validating Shapes, as many of the validation steps are possibly interchangeable. My plan is to start working on it as soon as I can, once I finish the course. So roughly in three weeks time I will delve into it.

I have no problem in collaborating, any help would be fantastic 😊

**Comment by mkatychev** [comment]
@angelip2303 it would be a good idea to make a board under https://github.com/weso/shapes-rs/projects and break up the work into issues/tickets this way people can see the progress and pick up work as needed

**Comment by labra** [comment]
@angelip2303 has alreadt started the SHACL implementation and has a small prototype...if he agrees, I would suggest to close this issue and add more specific issues for the different features that still need to be added.
