### ISSUE TITLE
Add more code quality checks

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [weso/shapes-rs#40]
Configure `cargo fmt` and `cargo clippy` will help to increase code quality.

**Comment by labra** [comment]
Indeed, that was in my TODO list...I saw you did a PR for that...would that PR solve this issue?

**Comment by MarcAntoine-Arnaud** [comment]
Yes it will address it.

**Comment by labra** [comment]
Thanks!, I merged your PR...I appreciate the cleaning of the code you hace accomplished...I hope I keep maintaining those rules...however, I am new with some of the tools, I am not sure if my future commits will automatically keep the quality checks or not...

I will leave this issue open by now until I have more confidence with the new quality checks...

Thanks a lot for the your contributions.

**Comment by MarcAntoine-Arnaud** [comment]
Hi,
Yes it's good to have these kind of tools.
As you've merged, the format is now required to merge.
For clippy, the goal is to finalise, it will be requested for each MR too then.

Regards

**Comment by MarcAntoine-Arnaud** [comment]
Hi @labra,
I have complete the clippy update. So now it will requires to be fine with it once it will be merged ;-)

**Comment by labra** [comment]
Thanks a lot for the PR...I have merged it already and will close this issue.
