### ISSUE TITLE
ambiguous licensing

### ISSUE THREAD

**Issue by jonassmedegaard** [weso/shapes-rs#62]
README.md states that licensing is Apache-2.0 or MIT,
but Cargo.toml states it is GPL-3.0-or-later.
Which is it?

**Comment by jonassmedegaard** [comment]
While at it, MIT license is included both as LICENSE and LICENSE-MIT, the former with an unfunished copyright statement lacking a cvopyright holder.

**Comment by labra** [comment]
Thanks a lot for reviewing this...you were right that the licenses were not properly declared.

I have changed the information in [Cargo.toml](https://github.com/weso/shapes-rs/blob/2e437bce085fb1105b2eac05e778a16afdaf588f/Cargo.toml#L5) to indicate that we have two licenses: MIT and Apache. If you think it would be better to add a GPL license, I would have no problem at all (I am not sure if it is possible to publish it with three licenses).

I have also edited the line in the [LICENSE-MIT](https://github.com/weso/shapes-rs/blob/2e437bce085fb1105b2eac05e778a16afdaf588f/LICENSE-MIT#L3) and [LICENSE-APACHE](https://github.com/weso/shapes-rs/blob/2e437bce085fb1105b2eac05e778a16afdaf588f/LICENSE-APACHE#L189) files adding me as copyright holder (I am not sure if I should add the other contributors...or how I could do it in a way that is more maintainable.

If you think this is OK, you can close the issue.

**Comment by jonassmedegaard** [comment]
In my understanding (I am not a lawyer, but has spent some years [staring at licenses](https://metacpan.org/pod/App::Licensecheck)), there is no benefit in adding GPL as an additional alternative license: GPL-3 is compatible with Apache-2.0 (but the inverse is not true: The resulting license when combining works licensed as GPL-3 and Apache-2.0 is GPL-3).

There is a problem in your editing the LICENSE-APACHE files, though: The Apache-2.0 license text is intended as a fixed document, which at the end contains an *example* of how to use it. You should **not** edit that example, but instead *reference* the document. In fact, the paragraph just above the line you edited states quite clearly how the authors recomend that you use the document.

MIT license, by comparison, is an older license, much shorter and intended to be declared verbatim each time it is used - originally it was not stored as an independent document, referenced from other files.

My recommendation is to treat both those files as static, and add [single-line SPDX copyright and licensing statements](https://reuse.software/tutorial/#step-2) to each and every file containing creative work - i.e. every code file and every "interesting" graphics file.

I also recommend to add your email address with your copyright statement, as a unique identifier.

Ideally, every legal entity (person or organisation) that has made substatial *creative* contribution should be listed as copyright holder. I cannot tell if those you consider constributors fit that bill or not, nor if your university fit that bill (I notice that you've added yourself, but list your university in `lib/docs/mkdocs.yml` - generally an employer should be listed if your creative work was done "paid by them" - i.e. if your contract with them says that they own your intelligense while you work for them - often american contracts are more aggressive in that regard, but in newer times it becomes more common for that predatory attitude towards ownership of labor).

**Comment by jonassmedegaard** [comment]
small nit: Instead of *copying* the license text documents, I suggest symlinking the files at the root of the project.

**Comment by labra** [comment]
> In my understanding (I am not a lawyer, but has spent some years [staring at licenses](https://metacpan.org/pod/App::Licensecheck)), there is no benefit in adding GPL as an additional alternative license: GPL-3 is compatible with Apache-2.0 (but the inverse is not true: The resulting license when combining works licensed as GPL-3 and Apache-2.0 is GPL-3).

So I understand it is fine for us to keep Apache 2.0 by now.
 
> There is a problem in your editing the LICENSE-APACHE files, though: The Apache-2.0 license text is intended as a fixed document, which at the end contains an _example_ of how to use it. You should **not** edit that example, but instead _reference_ the document. In fact, the paragraph just above the line you edited states quite clearly how the authors recomend that you use the document.

OK, I created PR #65 with the idea to revert those files. 

> My recommendation is to treat both those files as static, and add [single-line SPDX copyright and licensing statements](https://reuse.software/tutorial/#step-2) to each and every file containing creative work - i.e. every code file and every "interesting" graphics file.

I didn't know about the REUSE software...it looks interesting, and maybe we should adopt it in the future. I will create an specific  issue to keep track of that.

> I also recommend to add your email address with your copyright statement, as a unique identifier.

OK, I added my email to the LICENSE-MIT file. 

> Ideally, every legal entity (person or organisation) that has made substatial _creative_ contribution should be listed as copyright holder. I cannot tell if those you consider constributors fit that bill or not, nor if your university fit that bill (I notice that you've added yourself, but list your university in `lib/docs/mkdocs.yml` - generally an employer should be listed if your creative work was done "paid by them" - i.e. if your contract with them says that they own your intelligense while you work for them - often american contracts are more aggressive in that regard, but in newer times it becomes more common for that predatory attitude towards ownership of labor).

I think it is safe if we keep it by now with the individual contributors. Indeed, I didn't want to add myself alone and I prefer the idea of having a list of contributors in a file and refer to it from the Copyright as the "Shapes-rs" team, or something like that.

Do you know about some Rust project that has the license statements right that we could use as an example. Until now, my main source of inspiration is [Oxigraph](https://github.com/oxigraph/oxigraph/).

**Comment by labra** [comment]
I merged the PR with the changes...at this moment, I am a bit hesitant about adding the single line SPDX copyright statement to each source code file, mainly because we have a lot of files...

But once you consider that what we have now is more or less OK, we could close this issue and open a new specific one about that.

**Comment by jonassmedegaard** [comment]
Regarding project-wide licensing, Oxigraph handles copyright and licensing decently, in my opinion.

I agree that file-specific copyright and licensing statements is a different (and arguably less important) issue, sensible to track separately.
