### ISSUE TITLE
rdfsx lacks description

### ISSUE THREAD

**Issue by jonassmedegaard** [weso/shapes-rs#64]
Currently, `sx_cli/README.md` contains only a title, no description. Also, the crate metadata simply reuses the rather coarse synopsis form the project-wide workspace metadata.

For [my draft Debian packaging](http://bugs.debian.org/1073786) I have com up with the synopsis "CLI tool to process RDF with ShEx, SHACL or DCTAP", and the following description:

>  rdfsx is a command-line tool
> to inspect and validate RDF data
> using ShEx, SHACL or DCTAP.
>
> Resource Description Framework (RDF) is a standard model
> for data interchange on the Web.
>
> Shape Expressions (ShEx) is a data modelling language
> for defining schemas for RDF graphs.
>
> Shapes Constraint Language (SHACL) is a data modelling language
> for describing constraints for RDF graphs.
> SHACL is a W3C standard.
>
> Dublin Core Tabular Application Profiles (DCTAP) is a simple model
> for defining an application profile -
> i.e. metadata usage for a specific application.

Perhaps that might be helpful for the upstream README - and if not, then I am obviously interested as well, so I can correct my mistaken guesswork.

**Comment by labra** [comment]
I merged the PR #65 in which I added more information to the README.md following your description...I changed the word "standard" by "recommendation" because that's the term used in W3C.
