### ISSUE TITLE
subcommands lack one-line description

### ISSUE THREAD

**Issue by jonassmedegaard** [weso/shapes-rs#77]
Running `rdfsx --help` provides a list of subcommands, but they are not self-explanatory.

Ideally, next to each subcommand would be a one-line description introducing it, and when running `rdfsx SUBCOMMAND --help` at least that same introduction, but preferrably an additional elaboration in few paragraphs, would be at the top of the output, before listing arguments.

I have tried, with the help of the wiki pages, to construct the one-line descriptions (which also hints at where to expand with additional paragraphs):

```patch
Description: add initial descriptive sentence for each subcommand
Author: Jonas Smedegaard <dr@jones.dk>
Forwarded: not-needed
Last-Update: 2024-07-14
---
This patch header follows DEP-3: http://dep.debian.net/deps/dep3/
--- a/rdfsx_cli/src/cli.rs
+++ b/rdfsx_cli/src/cli.rs
@@ -24,6 +24,7 @@

 #[derive(Subcommand, Debug)]
 pub enum Command {
+    /// Process a ShapeMap
     Shapemap {
         #[arg(short = 'm', long = "shapemap", value_name = "ShapeMap file name")]
         shapemap: PathBuf,
@@ -50,6 +51,7 @@
         output: Option<PathBuf>,
     },

+    /// Show info about a ShEx schema
     Schema {
         #[arg(short = 's', long = "schema", value_name = "Schema file name")]
         schema: PathBuf,
@@ -84,6 +86,7 @@
         output: Option<PathBuf>,
     },

+    /// Validate a specific node with a shape in ShEx
     Validate {
         #[arg(short = 's', long = "schema", value_name = "Schema file name")]
         schema: PathBuf,
@@ -146,6 +149,7 @@
         output: Option<PathBuf>,
     },

+    /// Process RDF data
     Data {
         #[arg(short = 'd', long = "data", value_name = "RDF data path")]
         data: PathBuf,
@@ -166,6 +170,7 @@
         output: Option<PathBuf>,
     },

+    /// Show information about a node in an RDF file or a SPARQL endpoint
     Node {
         #[arg(short = 'n', long = "node")]
         node: String,
@@ -206,6 +211,7 @@
         output: Option<PathBuf>,
     },

+    /// Show information about a SHACL shapes graph
     Shacl {
         #[arg(short = 's', long = "shapes", value_name = "Shapes file name")]
         shapes: PathBuf,
@@ -234,6 +240,7 @@
         output: Option<PathBuf>,
     },

+    /// Convert from DCTap to JSON
     #[command(name = "dctap")]
     DCTap {
         #[arg(short = 'd', long = "DCTap file", value_name = "DCTap file name")]
@@ -263,6 +270,7 @@
         output: Option<PathBuf>,
     },

+    /// Convert from DCTap or ShEx to SPARQL, ShEx, UML or HTML
     #[command(name = "convert")]
     Convert {
         #[arg(short = 'm', long = "input-mode", value_name = "Input mode")]
```

Please note the places saying "Processing" which is purely made up, and probably needs rewording.

**Comment by jonassmedegaard** [comment]
Also, please note that the initial line is *not* a full sentence, so should not contain a trailing full stop (ideally it should also not have initial letter capitalized, but apparently that's how clap styles such one-liners itself, judging from the automatic "Print this message or the help of the given subcommand(s)".

**Comment by labra** [comment]
Thank...I really appreciate those suggestions to improve usebility of the tool.

I added those description lines and published a latest version yesterday (0.1.2), could you check if they are what you expected so we could close this issue?

**Comment by jonassmedegaard** [comment]
The proposed changes are maintained (and just now synced with v0.1.10) as a patch [here](https://salsa.debian.org/debian/rudof/-/blob/debian/latest/debian/patches/1001_help_strings.patch).

I do not push code to Github as a political principle, but perhaps I can persuade you to try out the decentralized git exchange [Radicle](https://radicle.xyz/guides/user) - it integrates seemlessly with git (at least on my Debian system) and should only involve you (or anyone permitted, after the initial push) changing your `git push` to `git push && git push rad`, and I am then more than happy to share my change proposals there, wheren you can accept them by doing `git pull rad && git push`

**Comment by labra** [comment]
Tnanks a lot for the suggestion on the description of the commands, it makes a lot of sense for me.

About using radicle, I was looking at it and it seems nice. I started [this discussion](https://github.com/weso/shapes-rs/discussions/111) in case more people want to express their opinion. As I understand, it would require me to run:

```
rad init
```

in the root of the project and after that, try to keep the remote rad up-to-date, right? 

I think you are only suggesting to keep rad as another remote, not to replace github by rad, is that also right? At this moment, I would prefer that option, I mean, to keep github and to add support for `radicle` so other contributors who don't want to use github, can also contribute...

**Comment by jonassmedegaard** [comment]
Looks good to me. Thanks!
