### ISSUE TITLE
uses two branches of oxigraph crates

### ISSUE THREAD

**Issue by jonassmedegaard** [weso/shapes-rs#83]
This project uses both stable crate oxigraph v0.3 and alpha versions of underlying crates oxrdf etc.

I think it is better to move to the newer oxigraph also for the main crate, to avoid duplicate code (and to ease packaging for Debian, which provides only the newer oxigraph v0.4 by now).

[Here](https://salsa.debian.org/debian/rdfsx/-/blob/debian/latest/debian/patches/1003_oxigraph.patch) is my attempt at modernizing, in case that is helpful - it compiles, but I am uncertain if the result is functionally correct.

**Comment by labra** [comment]
Done at PR #86
