### ISSUE TITLE
subcommand convert creates empty output file on failure

### ISSUE THREAD

**Issue by jonassmedegaard** [weso/shapes-rs#90]
Executing `rdfsx convert -m dctap -x uml -f csv -s book.csv -r svg -o book.svg` (from within the examples directory) fails with an error message that the prefix dct is not understood (see #92).
Regardless of the operation failing, however, the output file is created, with empty content.

I would expect that no output file would be created if the operation could not succeed.

**Comment by labra** [comment]
Yes, you are right, it shouldn't create the file.

**Comment by labra** [comment]
Solved in PR #96
